# Generated by Django 3.2.9 on 2021-11-18 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='processTracker',
            fields=[
                ('userEmail', models.CharField(max_length=100)),
                ('procName', models.CharField(blank=True, max_length=100)),
                ('procId', models.IntegerField(primary_key=True, serialize=False)),
                ('timeCreated', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='systems',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('winHostname', models.CharField(blank=True, max_length=100)),
                ('winUsername', models.CharField(blank=True, max_length=100)),
                ('winPassword', models.CharField(blank=True, max_length=100)),
                ('winBootIndex', models.IntegerField()),
                ('debHostname', models.CharField(blank=True, max_length=100)),
                ('debUsername', models.CharField(blank=True, max_length=100)),
                ('debPassword', models.CharField(blank=True, max_length=100)),
                ('debBootIndex', models.IntegerField()),
                ('ubuHostname', models.CharField(blank=True, max_length=100)),
                ('ubuUsername', models.CharField(blank=True, max_length=100)),
                ('ubuPassword', models.CharField(blank=True, max_length=100)),
                ('ubuBootIndex', models.IntegerField()),
                ('remark', models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='vbios',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chipName', models.CharField(max_length=100)),
                ('memoryType', models.CharField(max_length=100)),
                ('boardName', models.CharField(max_length=100)),
                ('romName', models.CharField(max_length=100)),
            ],
        ),
    ]
