# Generated by Django 3.2.9 on 2021-12-17 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_tool', '0005_auto_20211217_0222'),
    ]

    operations = [
        migrations.AlterField(
            model_name='processtracker',
            name='timeCreated',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
